name: RS-ServerAdmin
version: ${project.version}
main: com.rsscripting.serveradmin.RSServerAdmin
api-version: '1.21'

author: Big Pappa
contributors:
  - Atlas

commands:
  rsadmin:
    description: Open RS-ServerAdmin